// Constants for HVAC Pro Classifier

export const C = {
  bg: "var(--bg)",
  surface: "var(--surface)",
  surface2: "var(--surface2)",
  border: "var(--border)",
  borderMd: "var(--border-md)",
  text: "var(--text)",
  textMuted: "var(--text-muted)",
  textDim: "var(--text-dim)",
  accent: "var(--accent)",
  accentBg: "var(--accent-bg)",
  success: "var(--success)",
  successBg: "var(--success-bg)",
  danger: "var(--danger)",
  dangerBg: "var(--danger-bg)",
  warning: "var(--warning)",
  warningBg: "var(--warning-bg)",
};

export const CLS_COLORS = {
  REPUESTO:          { bg: '#fef3c7', text: '#92400e', border: '#f59e0b' },
  ACCESORIO:         { bg: '#ede9fe', text: '#4c1d95', border: '#8b5cf6' },
  PRODUCTO_COMPLETO: { bg: '#d1fae5', text: '#064e3b', border: '#10b981' },
  SERVICIO:          { bg: '#e0e7ff', text: '#1e1b4b', border: '#6366f1' },
  OTRO:              { bg: '#f1f5f9', text: '#475569', border: '#94a3b8' },
};

export const CLS = {
  REPUESTO: { color: C.warning, bg: CLS_COLORS.REPUESTO.bg, text: CLS_COLORS.REPUESTO.text, icon: "⚙️", label: "Repuesto" },
  ACCESORIO: { color: C.accent, bg: CLS_COLORS.ACCESORIO.bg, text: CLS_COLORS.ACCESORIO.text, icon: "🔩", label: "Accesorio" },
  PRODUCTO_COMPLETO: { color: C.success, bg: CLS_COLORS.PRODUCTO_COMPLETO.bg, text: CLS_COLORS.PRODUCTO_COMPLETO.text, icon: "📦", label: "Prod. Completo" },
  SERVICIO: { color: "#6366f1", bg: CLS_COLORS.SERVICIO.bg, text: CLS_COLORS.SERVICIO.text, icon: "🔧", label: "Servicio" },
  OTRO: { color: C.textMuted, bg: CLS_COLORS.OTRO.bg, text: CLS_COLORS.OTRO.text, icon: "📋", label: "Otro" },
};

export const DEFAULT_RULES = [
  // Repuestos keywords
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'repuesto', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'rep.', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'diafragma', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'electrodo', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'membrana', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'junta', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'oring', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'o-ring', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'empaquetadura', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'válvula', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'valvula', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'resistencia', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'termocupla', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'termopar', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'piloto', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'bujía', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'bujia', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'bobina', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'presostato', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'sensor', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'sonda', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'plaqueta', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'placa', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'display', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'perilla', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'manija', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'bisagra', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'resorte', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'arandela', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'tornillo', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'tuerca', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'bulón', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'bulon', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'retén', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'reten', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'rodamiento', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'ruleman', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'correa', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'cadena repuesto', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'carburador', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'cigüeñal', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'pistón', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'piston', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'biela', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'engranaje', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'piñón', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'pinon', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'escobilla', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'carbón', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'carbon', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'capacitor', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'condensador', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'relay', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'relé', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'rele', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'fusible', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'interruptor repuesto', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'micro', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'microswitch', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'ficha electro', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'conector para', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'inyector', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'quemador rep', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'unidad magnética', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'unidad magnetica', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'chicote', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'filtro deshidratador', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'vaina', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'encendido para', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'conjunto quemador', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'divisor', peso: 15 },
  { tipo: 'REPUESTO', nivel: 'keyword', valor: 'espada orgon', peso: 15 },

  // Accesorios keywords
  { tipo: 'ACCESORIO', nivel: 'keyword', valor: 'acc.', peso: 10 },
  { tipo: 'ACCESORIO', nivel: 'keyword', valor: 'accesorio', peso: 10 },
  { tipo: 'ACCESORIO', nivel: 'keyword', valor: 'adaptador', peso: 10 },
  { tipo: 'ACCESORIO', nivel: 'keyword', valor: 'cupla', peso: 10 },
  { tipo: 'ACCESORIO', nivel: 'keyword', valor: 'racor', peso: 10 },
  { tipo: 'ACCESORIO', nivel: 'keyword', valor: 'reducción', peso: 10 },
  { tipo: 'ACCESORIO', nivel: 'keyword', valor: 'reduccion', peso: 10 },
  { tipo: 'ACCESORIO', nivel: 'keyword', valor: 'codo', peso: 10 },
  { tipo: 'ACCESORIO', nivel: 'keyword', valor: 'tee', peso: 10 },
  { tipo: 'ACCESORIO', nivel: 'keyword', valor: 'curva', peso: 10 },
  { tipo: 'ACCESORIO', nivel: 'keyword', valor: 'niple', peso: 10 },
  { tipo: 'ACCESORIO', nivel: 'keyword', valor: 'brida', peso: 10 },
  { tipo: 'ACCESORIO', nivel: 'keyword', valor: 'abrazadera', peso: 10 },
  { tipo: 'ACCESORIO', nivel: 'keyword', valor: 'grampa', peso: 10 },
  { tipo: 'ACCESORIO', nivel: 'keyword', valor: 'conector universal', peso: 10 },
  { tipo: 'ACCESORIO', nivel: 'keyword', valor: 'detentor', peso: 10 },
  { tipo: 'ACCESORIO', nivel: 'keyword', valor: 'desfangador', peso: 10 },

  // Producto Completo keywords
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'equipo', peso: 20 },
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'caldera', peso: 20 },
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'salamandra', peso: 20 },
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'estufa', peso: 20 },
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'radiador elemento', peso: 20 },
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'bomba', peso: 20 },
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'presurizador', peso: 20 },
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'electrobomba', peso: 20 },
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'compresor', peso: 20 },
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'extractor', peso: 20 },
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'ventilador', peso: 20 },
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'aire acondicionado', peso: 20 },
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'split', peso: 20 },
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'cortacerco', peso: 20 },
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'motosierra', peso: 20 },
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'desmalezadora', peso: 20 },
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'cortacesped', peso: 20 },
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'escalera', peso: 20 },
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'taladro', peso: 20 },
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'amoladora', peso: 20 },
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'soldadora', peso: 20 },
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'filtro de agua', peso: 20 },
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'purificador', peso: 20 },
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'ablandador', peso: 20 },
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'termotanque', peso: 20 },
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'calefón', peso: 20 },
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'calefon', peso: 20 },
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'cortina', peso: 20 },
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'pileta', peso: 20 },
  { tipo: 'PRODUCTO_COMPLETO', nivel: 'keyword', valor: 'tanque', peso: 20 },

  // Rubro/Subrubro Patterns
  { tipo: 'REPUESTO', nivel: 'rubro_pattern', valor: '^rep\\.', peso: 40 },
  { tipo: 'REPUESTO', nivel: 'rubro_pattern', valor: 'repuesto', peso: 40 },
  { tipo: 'ACCESORIO', nivel: 'rubro_pattern', valor: '^acc\\.', peso: 40 },
  { tipo: 'REPUESTO', nivel: 'subrubro_pattern', valor: '^acc\\.', peso: 30 },
  { tipo: 'REPUESTO', nivel: 'subrubro_pattern', valor: '^rep\\.', peso: 30 },
  { tipo: 'REPUESTO', nivel: 'subrubro_pattern', valor: 'diafragma', peso: 30 },
  { tipo: 'REPUESTO', nivel: 'subrubro_pattern', valor: 'electrodo', peso: 30 },
  { tipo: 'REPUESTO', nivel: 'subrubro_pattern', valor: 'plaqueta', peso: 30 },
  { tipo: 'REPUESTO', nivel: 'subrubro_pattern', valor: 'sensor', peso: 30 },
  { tipo: 'REPUESTO', nivel: 'subrubro_pattern', valor: 'membrana', peso: 30 },
  { tipo: 'REPUESTO', nivel: 'subrubro_pattern', valor: 'filtro', peso: 30 },
];

export const PAGE_SIZE = 50;
